version: '3.8'

services:
  browser-bot:
    build:
      context: ../../services/meeting_agent/browser_bot
      dockerfile: Dockerfile
    image: clerk-browser-bot:latest
    container_name: clerk-browser-bot-dev
    environment:
      - MEETING_URL=${MEETING_URL}
      - BOT_NAME=${BOT_NAME:-Clerk AI Bot}
      - PLATFORM=${PLATFORM:-google_meet}
      - RT_GATEWAY_URL=${RT_GATEWAY_URL:-ws://localhost:8001}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8000}
      - MEETING_ID=${MEETING_ID}
      - SESSION_ID=${SESSION_ID}
      - JOIN_TIMEOUT_SEC=${JOIN_TIMEOUT_SEC:-60}
      - AUDIO_SAMPLE_RATE=${AUDIO_SAMPLE_RATE:-16000}
      - AUDIO_CHANNELS=${AUDIO_CHANNELS:-1}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - BROWSER_USE_API_KEY=${BROWSER_USE_API_KEY:-}
    # Required for Playwright in Docker
    shm_size: '2g'
    # For audio routing and display
    network_mode: "host" # Use host network for easier audio routing and display access
    cap_add:
      - SYS_ADMIN # Required for some browser operations
    security_opt:
      - seccomp:unconfined # Required for Chromium in some environments
    devices:
      - /dev/snd:/dev/snd # Expose sound devices for audio capture/playback
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # For X server if running non-headless (optional)
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '${BOT_CONTAINER_CPU:-1.0}' # 1 CPU core
          memory: '${BOT_CONTAINER_MEMORY:-2048M}' # 2GB RAM
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3